//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectA
{
    using System;
    using System.Collections.Generic;
    
    public partial class additional_cost
    {
        public int addi_cost_id { get; set; }
        public Nullable<int> pond_id { get; set; }
        public Nullable<double> additional_cost_p { get; set; }
        public string additional_cost_name { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
