//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectA
{
    using System;
    using System.Collections.Generic;
    
    public partial class fish_set
    {
        public int fish_set_id { get; set; }
        public Nullable<int> pond_id { get; set; }
        public Nullable<int> fish_id { get; set; }
        public Nullable<int> fish_quantity { get; set; }
        public string fish_contributore_name { get; set; }
        public Nullable<double> fish_price { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string user_id { get; set; }
        public Nullable<double> fish_weight { get; set; }
    }
}
