//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectA
{
    using System;
    using System.Collections.Generic;
    
    public partial class pond_detail
    {
        public int pond_details_id { get; set; }
        public Nullable<int> pond_id { get; set; }
        public Nullable<double> total_set_fish { get; set; }
        public Nullable<double> total_sell_fish { get; set; }
        public Nullable<double> total_avail_fish { get; set; }
        public string user_id { get; set; }
    }
}
